layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 20
  exclude:
    archived: false
    forks: true
    projects:
      - pengyou-flutter
      - nested-navigation
      - pengyou-data-generator
      - pleco-viewer
      - iccbc19

repo_descriptions:
  - name: stroke-order-animator
    text: This Flutter project was a great opportunity for me to practice <b>test-driven development</b> and <b>continuous integration/deployment</b>. Github actions automatically run a test suite for every pull request to the master branch of the repository and publish the package on pub.dev when all tests pass and the version number has been incremented.

  - name: ns18
    text: The final project of the <b>network security</b> course I took during my exchange semester at Tsinghua University tested my understanding of how the <b>internet, firewalls, and deep packet inspection</b> work.

  - name: pengyou
    text: Writing a Chinese learning app is definitely a great way to procrastinate when one should actually be studying Chinese. This project was my first deep dive into <b>mobile development</b> by writing a <b>native Android app</b> and ultimately publishing it to the Google Play store.

  - name: dl4cv
    text: A shared effort by a fellow student and me, this project was part of a course on advanced deep learning for <b>computer vision</b>. We applied <b>variational auto-encoders</b> with a special differentiable bottleneck to recover disentangled and physically interpretable latent representations from image sequences.

  - name: tingting
    text: Concurrently pondering <b>protein sequence alignment</b> and how to improve my listening comprehension led me to writing this little <b>Flutter</b> app. It uses the Smith-Waterman algorithm for local sequence alignment to automatically compare what one has written during a dictation with a ground truth.

  - name: deep-image-restoration
    text: This project is a <b>PyTorch</b> implementation of a UNet for image restoration tasks like pixel interpolation. It also incorporates an on-demand learning approach that improves convergence speed and stability by automatically choosing training samples with just the right difficulty.

  - name: cb18
    text: The final project of the <b>computational biology</b> course I took during my exchange semester at Tsinghua University aims to improve the performance of synergy predictions of drug combinations for cancer treatment by applying dimensionality reduction techniques to the dataset.

about:
  - name: D
    position: C
    period: O

ending:
  - name: D
    position: C
    period: O

contact:
  - name: D
    position: C
    period: O

works:
  - name: Porsche • Stuttgart, Germany
    position: Development Engineer
    position2: Responsible for the 48V electrical energy management software across all model ranges • Implementation of processes inside the Volkswagen group to minimize power consumption of onboard electrical components
    period: October 2015 - September 2017

  - name: Porsche • Stuttgart, Germany
    position: Working student in Porsche's integrated degree program
    position2: Project work in different departments, most notably contributing to Porsche InnoDrive
    period: October 2017 - December 2019




education:
  - name: Technical University of Munich • Munich, Germany
    position: Graduate studies in robotics and AI
    position2: Machine learning fundamentals • Deep learning in computer vision, robotics, and computational biology • Bare-bones microcontroller programming in C
    period: October 2017 - April 2021

  - name: LTL Mandarin School • Shanghai, China
    position: 400 hours of 1-on-1 Mandarin lessons
    position2: HSK 5 test passed with 274/300 points in Dec. 2019
    period: September 2019 - January 2020

  - name: Tsinghua University • Beijing, China
    position: Exchange semester
    position2: Deep learning in network security and computational biology • Mandarin
    period: September 2018 - January 2019

  - name: Baden-Wuerttemberg Cooperative State University • Stuttgart, Germany
    position: Undergraduate studies in Electrical Engineering
    position2: Automation • Control systems • E-mobility
    position3: "Thesis topic: Analysis of predictive operation strategies for reducing the energy consumption of electric vehicles"
    period: September 2012 - September 2015



topics:
  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/python/python.png

  - name: JavaScript
    web_url: https://github.com/topics/javascript
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/javascript/javascript.png

social_media:
  #stackoverflow: 13520207
  linkedin: felipe-peter-4755541bb
  # facebook: your_username
  # instagram: your_username 
  # behance: your_username
  # dribbble: your_username
  # hackerrank: your_username
  # keybase: your_username
  # mastodon: your_username
  # telegram: your_username
  # twitter: your_username
  medium: Mr_Pepe
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username


