layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: true
    forks: false
    projects:
      - amawest.github.io

social_media:
  facebook: amanda.west.148553
  linkedin: amanda-west-a33260131/
  instagram: a_west213
  medium: amawest
  # behance: your_username
  # dribbble: your_username
  # hackerrank: your_username
  # keybase: your_username
  # mastodon: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username


