layout: sidebar
style: light

plugins: 
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope: 
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 20
  exclude:
    archived: false
    forks: true
    projects:
      - pengyou-flutter
      - nested-navigation
      - pengyou-data-generator
      - pleco-viewer
      - iccbc19
  
about:
  - name: D
    position: C
    period: O

ending:
  - name: D
    position: C
    period: O

contact:
  - name: D
    position: C
    period: O

works:
  - name: Data Visualization Specialist
    position: • Ann Arbor, Michigan
    position2: Clark Data Labs
    period: October 2019 - April 2020

  - name: Research Assistant
    position: • Ann Arbor, Michigan
    position2: University of Michigan Economics Department
    period: October 2017 - December 2019

  


education:
  - name: Technical University of Munich • Munich, Germany
    position: Graduate studies in "Robotics, Cognition, Intelligence"
    position2: Machine learning fundamentals • Deep learning in computer vision, robotics, and computational biology • Bare-bones microcontroller programming in C
    period: October 2017 - April 2021

  - name: LTL Mandarin School • Shanghai, China
    position: 400 hours of 1-on-1 Mandarin lessons
    position2: HSK 5 test passed with 274/300 points in Dec. 2019
    period: September 2019 - January 2020  
    
  - name: Tsinghua University • Beijing, China
    position: Exchange semester
    position2: Deep learning in network security and computational biology • Mandarin
    period: September 2018 - January 2019

  - name: Baden-Wuerttemberg Cooperative State University • Stuttgart, Germany
    position: Undergraduate studies in Electrical Engineering
    position2: Automation • Control systems • E-mobility
    position3: "Thesis topic: Analysis of predictive operation strategies for reducing the energy consumption of electric vehicles"
    period: September 2012 - September 2015
  


topics:
  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/python/python.png

  - name: JavaScript
    web_url: https://github.com/topics/javascript
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/javascript/javascript.png

social_media:
  #stackoverflow: 13520207
  linkedin: felipe-peter-4755541bb
  # facebook: your_username
  # instagram: your_username 
  # behance: your_username
  # dribbble: your_username
  # hackerrank: your_username
  # keybase: your_username
  # mastodon: your_username
  # telegram: your_username
  # twitter: your_username
  medium: Mr_Pepe
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username


