layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope: 
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: false
    projects:
      - amawest.github.io
      - VisualizingTheFuture2
      - VisualizingtheFuture.github.io

about:
  - name: Data 
    position: C
    period: O

ending:
  - name: Data 
    position: C
    period: O

works:
  - name: Data Visualization Specialist
    position: • Ann Arbor, Michigan
    position2: Clark Data Labs
    period: October 2019 - April 2020

  - name: Research Assistant
    position: • Ann Arbor, Michigan
    position2: University of Michigan Economics Department
    period: October 2017 - December 2019

  - name: Grant Writing Intern
    position: • Tirana, Albania
    position2: Ministry of Economic Development, Tourism, Trade & Entrepreneurship
    period: June 2017 - August 2017 

  - name: Community Organization Intern
    position: • Ann Arbor, Michigan
    position2: Clean Water Action
    period: July 2016 - August 2016

education:
  - name: University of Virginia, School of Data Science
    position: M.S. in Data Science
    period: July 2020 - May 2021

  - name: University of Michigan, College of Literature, Science, and the Arts
    position: B.S. in Economics with Honors •  Minor in Mathematics
    position2: Playing by the Rules; How had the TRIPS Agreement Affected IP Adherence? (thesis)
    period: September 2016 - May 2020

  - name: Beijing Language and Culture Institute (北京语言大学)
    position: Study Abroad (Intensive Mandarin)
    period: August 2018 - December 2018

topics:
  - name: R
    web_url: https://github.com/topics/R
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/r/r.png

  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/python/python.png

  - name: C++
    web_url: https://github.com/topics/cpp
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/cpp/cpp.png

  - name: HTML
    web_url: https://github.com/topics/HTML
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/html/html.png

  - name: CSS
    web_url: https://github.com/topics/CSS
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

  - name: JavaScript
    web_url: https://github.com/topics/javascript
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/javascript/javascript.png

social_media:
  #medium: amawest
  #stackoverflow: 13520207
  linkedin: amanda-west-a33260131/
  # facebook: amanda.west.148553
  # instagram: a_west213 
  # behance: your_username
  # dribbble: your_username
  # hackerrank: your_username
  # keybase: your_username
  # mastodon: your_username
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username


